use std::env;

fn main() {
    if env::var_os("CARGO_FEATURE_C_BINDING").is_none() {
        return;
    }

    generate_c_header();
}

#[cfg(feature = "c-binding")]
fn generate_c_header() {
    use std::path::PathBuf;

    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let header_path = out_dir.join("sentra.h");

    let config = cbindgen::Config::from_root_or_default(&crate_dir);

    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_config(config)
        .with_language(cbindgen::Language::C)
        .with_include_guard("SENTRA_H")
        .with_autogen_warning("/* Auto-generated by cbindgen — do not edit by hand. */")
        .with_documentation(true)
        .generate()
        .expect("cbindgen: unable to generate C header")
        .write_to_file(&header_path);

    println!(
        "cargo:warning=Generated sentra.h → {}",
        header_path.display()
    );
}

#[cfg(not(feature = "c-binding"))]
fn generate_c_header() {}
